export type RemoteAction = 'upgrade' | 'attack' | 'heal' | 'finish' | 'guard' | 'ultimate'
export type WordPoolSize = 300 | 1200 | 5000
export type RoundLimit = 10 | 20 | 30
export type RemoteStatChange = { playerId:string; name:string; hp?:number; maxHp?:number; atk?:number; def?:number; shield?:number; guard?:'on'|'off'; ko?:boolean }
export type RemoteActionResult = { id:string; playerId:string; playerName:string; action?:RemoteAction; coefficient:number; correct:boolean; critical:boolean; ultimate:boolean; text:string; changes:RemoteStatChange[] }
export type RemotePlayer = { id:string; name:string; host:boolean; jobId?:string; hp:number; maxHp:number; atk:number; def:number; alive:boolean; guard:boolean; guardCharges?:number; guardMultiplier?:number; shield?:number; ultimateUsed?:boolean; ultimateUses?:number; actionsTaken?:number; action?:RemoteAction; answered?:boolean; coefficient?:number; answeredAt?:number; answerCorrect?:boolean; quizIndex?:number; roundCorrect?:number; roundAnswered?:number; quizQuestionStartedAt?:number; questionsSeen?:number; correctAnswers?:number; damageDone?:number; healingDone?:number }
export type RemoteQuestion = { id:number; word:string; choices:string[] }
export type RemoteRoomState = { roomId:string; phase:'lobby'|'jobs'|'battle'|'result'; battlePhase:'action'|'quiz'|'resolve'; round:number; maxRounds:RoundLimit; questionIndex:number; usedQuestionIds?:number[]; question?:RemoteQuestion; questions?:RemoteQuestion[]; wordPoolSize:WordPoolSize; jobsEndsAt?:number; actionEndsAt?:number; quizEndsAt?:number; resolveEndsAt?:number; resolveQueue?:string[]; resolveIndex?:number; currentResult?:RemoteActionResult; players:RemotePlayer[]; log:string[] }
export type AnswerResponse = RemoteRoomState & { answerFeedback?:{ correct:boolean; correctAnswer:string; questionNumber:number } }
const configuredBaseUrl=()=>(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'')
const getBaseUrl=()=>{const configured=configuredBaseUrl();if(configured)return configured;if(typeof window==='undefined')return '';if(window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1')return '';return window.location.origin}
export const hasMultiplayerApi=()=>Boolean(getBaseUrl())
async function apiRequest<T>(path:string,body?:unknown):Promise<T>{const baseUrl=getBaseUrl();if(!baseUrl)throw new Error('多人伺服器尚未設定');const response=await fetch(baseUrl+path,{method:body?'POST':'GET',headers:{'content-type':'application/json','accept':'application/json'},body:body?JSON.stringify(body):undefined});const raw=await response.text();let data:any=null;try{data=raw?JSON.parse(raw):null}catch{const hint=response.status>=500?'伺服器暫時異常，請再試一次':'伺服器回傳格式異常';throw new Error(hint)}if(!response.ok)throw new Error(data?.error||'連線失敗');return data as T}
function sendLeaveBeacon(roomId:string,playerId:string){const baseUrl=getBaseUrl();if(!baseUrl||!roomId||!playerId)return false;const body=new Blob([JSON.stringify({playerId})],{type:'application/json'});return navigator.sendBeacon(`${baseUrl}/api/rooms/${encodeURIComponent(roomId)}/leave`,body)}
function clearRoomSession(){localStorage.removeItem('hero-room-id');localStorage.removeItem('hero-player-id')}

export function connectRoom(roomId:string,onState:(state:RemoteRoomState)=>void,onConnection?:(connected:boolean)=>void){const baseUrl=getBaseUrl();if(!baseUrl)return()=>undefined;const wsBase=baseUrl.replace(/^http/,'ws');const playerId=localStorage.getItem('hero-player-id')||'';let stopped=false,socket:WebSocket|null=null,pingTimer:number|undefined,exitSent=false,opened=false
 const abandonRoom=()=>{if(exitSent)return;exitSent=true;stopped=true;if(playerId)sendLeaveBeacon(roomId,playerId);clearRoomSession();if(pingTimer)window.clearInterval(pingTimer);socket?.close();socket=null}
 const goHome=()=>{abandonRoom();if(location.pathname!=='/'||location.search||location.hash)window.location.replace('/');else window.location.reload()}
 const onVisibilityChange=()=>{if(document.visibilityState==='hidden')goHome()}
 const onPageHide=()=>abandonRoom()
 const onOffline=()=>goHome()
 document.addEventListener('visibilitychange',onVisibilityChange);window.addEventListener('pagehide',onPageHide);window.addEventListener('offline',onOffline)
 socket=new WebSocket(`${wsBase}/api/rooms/${encodeURIComponent(roomId)}/ws?playerId=${encodeURIComponent(playerId)}`)
 socket.onopen=()=>{opened=true;onConnection?.(true);socket?.send('ping');pingTimer=window.setInterval(()=>{if(socket?.readyState===WebSocket.OPEN)socket.send('ping')},15000)}
 socket.onmessage=(event)=>{if(event.data==='pong')return;try{const payload=JSON.parse(event.data);if(payload?.type==='state'&&payload.state){const stillHere=payload.state.players?.some((p:RemotePlayer)=>p.id===playerId);if(!stillHere){goHome();return}onState(payload.state)}}catch{}}
 socket.onclose=()=>{onConnection?.(false);if(pingTimer)window.clearInterval(pingTimer);if(!stopped&&opened)goHome()}
 socket.onerror=()=>socket?.close()
 return()=>{stopped=true;document.removeEventListener('visibilitychange',onVisibilityChange);window.removeEventListener('pagehide',onPageHide);window.removeEventListener('offline',onOffline);if(pingTimer)window.clearInterval(pingTimer);socket?.close();socket=null}}

export const multiplayerApi={health:()=>apiRequest<{ok:boolean}>('/api/health'),state:(roomId:string)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/state`),join:(roomId:string,name:string,playerId?:string)=>apiRequest<{playerId:string;state:RemoteRoomState}>(`/api/rooms/${encodeURIComponent(roomId)}/join`,{name,playerId}),setWordPool:(roomId:string,playerId:string,wordPoolSize:WordPoolSize)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/word-pool`,{playerId,wordPoolSize}),setRoundLimit:(roomId:string,playerId:string,maxRounds:RoundLimit)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/round-limit`,{playerId,maxRounds}),beginJobs:(roomId:string,playerId:string)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/begin-jobs`,{playerId}),chooseJob:(roomId:string,playerId:string,jobId:string)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/choose-job`,{playerId,jobId}),start:(roomId:string,playerId:string)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/start`,{playerId}),action:(roomId:string,playerId:string,action:RemoteAction)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/action`,{playerId,action}),answer:(roomId:string,playerId:string,choice:string,coefficient:number)=>apiRequest<AnswerResponse>(`/api/rooms/${encodeURIComponent(roomId)}/answer`,{playerId,choice,coefficient}),tick:(roomId:string)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/tick`,{}),leave:(roomId:string,playerId:string)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/leave`,{playerId}),leaveBeacon:sendLeaveBeacon,reset:(roomId:string,playerId:string)=>apiRequest<RemoteRoomState>(`/api/rooms/${encodeURIComponent(roomId)}/reset`,{playerId})}