import { mkdir, writeFile } from 'node:fs/promises'
import * as OpenCC from 'opencc-js'

const sources = {
  frequency: 'https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english.txt',
  junior: 'https://raw.githubusercontent.com/KyleBing/english-vocabulary/master/初中-乱序.json',
  senior: 'https://raw.githubusercontent.com/KyleBing/english-vocabulary/master/高中-乱序.json',
}

const converter = OpenCC.Converter({ from: 'cn', to: 'tw' })
const fetchText = async url => {
  const r = await fetch(url)
  if (!r.ok) throw new Error(`Vocabulary source failed: ${r.status} ${url}`)
  return r.text()
}
const cleanMeaning = value => converter(String(value ?? '')
  .replace(/\s+/g, ' ')
  .replace(/^[a-z]+\.\s*/i, '')
  .split(/[；;]/)[0]
  .split(/\n/)[0]
  .trim())
const makeMap = rows => {
  const map = new Map()
  for (const row of rows) {
    const word = String(row.word ?? '').trim().toLowerCase()
    const raw = Array.isArray(row.translations) ? row.translations[0]?.translation : row.translation
    const meaning = cleanMeaning(raw)
    if (/^[a-z][a-z'-]{1,24}$/.test(word) && meaning && meaning.length <= 28 && !map.has(word)) map.set(word, meaning)
  }
  return map
}
const uniquePairs = (frequency, primary, fallback, count) => {
  const out = [], used = new Set()
  const add = word => {
    const w = word.toLowerCase(), meaning = primary.get(w) ?? fallback?.get(w)
    if (!meaning || used.has(w)) return
    used.add(w); out.push([w, meaning])
  }
  for (const w of frequency) { add(w); if (out.length >= count) break }
  if (out.length < count) for (const w of primary.keys()) { add(w); if (out.length >= count) break }
  if (out.length < count && fallback) for (const w of fallback.keys()) { add(w); if (out.length >= count) break }
  if (out.length < count) throw new Error(`Only ${out.length}/${count} vocabulary items available`)
  return out.slice(0, count)
}

const [frequencyText, juniorText, seniorText] = await Promise.all(Object.values(sources).map(fetchText))
const frequency = frequencyText.split(/\r?\n/).map(x => x.trim().toLowerCase()).filter(Boolean)
const junior = makeMap(JSON.parse(juniorText))
const senior = makeMap(JSON.parse(seniorText))
const bank300 = uniquePairs(frequency, junior, senior, 300)
const bank1200 = uniquePairs(frequency, junior, senior, 1200)
const bank6000 = uniquePairs(frequency, senior, junior, 6000)

const file = `// AUTO-GENERATED by scripts/build-vocab.mjs. Do not edit by hand.\nexport type WordPoolSize = 300|1200|6000\ntype Pair = readonly [string,string]\nconst b300:Pair[]=${JSON.stringify(bank300)}\nconst b1200:Pair[]=${JSON.stringify(bank1200)}\nconst b6000:Pair[]=${JSON.stringify(bank6000)}\nconst banks:Record<WordPoolSize,Pair[]>={300:b300,1200:b1200,6000:b6000}\nconst mix=(a:number,b:number)=>((a*1664525+b*1013904223)>>>0)\nexport function getVocabularyQuestion(size:WordPoolSize,index:number){const bank=banks[size]??b300;const i=((index%bank.length)+bank.length)%bank.length;const [word,answer]=bank[i];let j=mix(i,size)%bank.length,k=mix(i+17,size+31)%bank.length;if(j===i)j=(j+1)%bank.length;if(k===i||k===j)k=(k+2)%bank.length;const choices=[answer,bank[j][1],bank[k][1]];for(let n=choices.length-1;n>0;n--){const p=mix(i+n,size+n)%(n+1);[choices[n],choices[p]]=[choices[p],choices[n]]}return{id:i+1,word,answer,choices}}\nexport const vocabularyCounts={300:b300.length,1200:b1200.length,6000:b6000.length} as const\n`
await mkdir('worker', { recursive: true })
await writeFile('worker/vocab.generated.ts', file, 'utf8')
console.log(`Vocabulary ready: ${bank300.length}/${bank1200.length}/${bank6000.length}`)
