import { DurableObject } from 'cloudflare:workers'
export interface Env { ROOMS: DurableObjectNamespace<GameRoom>; ASSETS: Fetcher }
type Phase='lobby'|'jobs'|'battle'|'result';type BattlePhase='action'|'quiz'|'resolve';type ActionName='upgrade'|'attack'|'heal'|'finish'|'guard';type WordPoolSize=300|1200|6000
type Player={id:string;name:string;host:boolean;jobId?:string;hp:number;maxHp:number;atk:number;def:number;alive:boolean;guard:boolean;action?:ActionName;answered?:boolean;coefficient?:number;lastSeen?:number}
type Question={id:number;word:string;answer:string;choices:string[]};type PublicQuestion=Omit<Question,'answer'>
type RoomState={roomId:string;phase:Phase;battlePhase:BattlePhase;round:number;questionIndex:number;question?:PublicQuestion;wordPoolSize:WordPoolSize;jobsEndsAt?:number;actionEndsAt?:number;quizEndsAt?:number;players:Player[];log:string[]}
const ACTION_MS=5000,QUIZ_MS=8000,JOBS_MS=30000,PRESENCE_MS=45000,SWEEP_MS=15000
const wordPoolSizes=new Set<WordPoolSize>([300,1200,6000])
const questions:Question[]=[{id:1,word:'brave',answer:'勇敢的',choices:['安靜的','勇敢的','飢餓的']},{id:2,word:'shield',answer:'盾牌',choices:['盾牌','箭矢','城堡']},{id:3,word:'heal',answer:'治療',choices:['逃跑','攻擊','治療']},{id:4,word:'victory',answer:'勝利',choices:['失敗','勝利','危險']},{id:5,word:'enemy',answer:'敵人',choices:['敵人','朋友','老師']},{id:6,word:'protect',answer:'保護',choices:['保護','破壞','尋找']},{id:7,word:'strong',answer:'強壯的',choices:['快速的','疲累的','強壯的']},{id:8,word:'attack',answer:'攻擊',choices:['防守','攻擊','等待']},{id:9,word:'magic',answer:'魔法',choices:['魔法','盔甲','道路']},{id:10,word:'survive',answer:'生存',choices:['投降','生存','睡覺']},{id:11,word:'sword',answer:'劍',choices:['弓','劍','盾牌']},{id:12,word:'danger',answer:'危險',choices:['安全','危險','和平']}]
const jobIds=['assassin','warrior','fighter','archer','priest','mage'];const jobs=new Set(jobIds);const actions=new Set<ActionName>(['upgrade','attack','heal','finish','guard'])
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'}})
const publicQuestion=(q:Question):PublicQuestion=>({id:q.id,word:q.word,choices:q.choices});const clampCoefficient=(v:number)=>Math.max(0,Math.min(4,Math.floor(v)))
export default{async fetch(request:Request,env:Env):Promise<Response>{if(request.method==='OPTIONS')return json({ok:true});const url=new URL(request.url);if(url.pathname==='/api/health')return json({ok:true,service:'hero-word-battle-api',version:'0.7.3'});const m=url.pathname.match(/^\/api\/rooms\/([^/]+)(\/.*)?$/);if(m){const roomId=decodeURIComponent(m[1]).slice(0,64),sub=m[2]||'/state',id=env.ROOMS.idFromName(roomId),stub=env.ROOMS.get(id),f=new URL(request.url);f.pathname=sub;f.searchParams.set('roomId',roomId);return stub.fetch(new Request(f,request))}return env.ASSETS.fetch(request)}}
export class GameRoom extends DurableObject<Env>{
 private stateData:RoomState|null=null
 private async getState(roomId?:string){if(this.stateData)return this.stateData;const stored=await this.ctx.storage.get<RoomState>('state');this.stateData=stored??{roomId:roomId||this.ctx.id.toString(),phase:'lobby',battlePhase:'action',round:0,questionIndex:0,wordPoolSize:300,players:[],log:[]};if(!wordPoolSizes.has(this.stateData.wordPoolSize))this.stateData.wordPoolSize=300;return this.stateData}
 private normalizeAfterLeave(s:RoomState){if(s.players.length&&!s.players.some(p=>p.host))s.players[0].host=true;if(!s.players.length){s.phase='lobby';s.battlePhase='action';s.round=0;s.question=undefined;s.log=[];s.jobsEndsAt=undefined;s.actionEndsAt=undefined;s.quizEndsAt=undefined}else if(s.phase==='jobs'&&s.players.length<2){s.phase='lobby';s.jobsEndsAt=undefined;for(const p of s.players)p.jobId=undefined}else if(s.phase==='battle'&&s.players.filter(p=>p.alive).length<=1)s.phase='result'}
 private activeSocketIds(){const ids=new Set<string>();for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment() as {playerId?:string}|null;if(a?.playerId)ids.add(a.playerId)}return ids}
 private pruneStale(s:RoomState){const cutoff=Date.now()-PRESENCE_MS,active=this.activeSocketIds(),before=s.players.length;s.players=s.players.filter(p=>active.has(p.id)||(typeof p.lastSeen==='number'&&p.lastSeen>=cutoff));if(s.players.length!==before){this.normalizeAfterLeave(s);return true}return false}
 private async save(s:RoomState){s.log=s.log.slice(-12);this.stateData=s;await this.ctx.storage.put('state',s);const deadline=s.phase==='jobs'?s.jobsEndsAt:s.phase==='battle'?(s.battlePhase==='action'?s.actionEndsAt:s.battlePhase==='quiz'?s.quizEndsAt:undefined):undefined;const presence=s.players.length?Date.now()+SWEEP_MS:undefined;const alarm=deadline&&presence?Math.min(deadline,presence):deadline??presence;if(alarm)await this.ctx.storage.setAlarm(alarm);else await this.ctx.storage.deleteAlarm();const payload=JSON.stringify({type:'state',state:s});for(const ws of this.ctx.getWebSockets()){try{ws.send(payload)}catch{}}}
 private beginAction(s:RoomState){s.battlePhase='action';s.question=undefined;s.quizEndsAt=undefined;s.actionEndsAt=Date.now()+ACTION_MS;for(const p of s.players){p.action=undefined;p.answered=false;p.coefficient=undefined}}
 private startBattle(s:RoomState){s.phase='battle';s.jobsEndsAt=undefined;s.round=1;s.questionIndex=0;s.log=['戰鬥開始！'];for(const p of s.players){p.hp=100;p.maxHp=100;p.atk=10;p.def=5;p.alive=true;p.guard=false}this.beginAction(s)}
 private fillRandomJobs(s:RoomState){const used=new Set(s.players.map(p=>p.jobId).filter(Boolean) as string[]);for(const p of s.players.filter(p=>!p.jobId)){const available=jobIds.filter(j=>!used.has(j));const pick=available[Math.floor(Math.random()*available.length)];p.jobId=pick;used.add(pick)}}
 private prepareQuiz(s:RoomState){s.battlePhase='quiz';s.actionEndsAt=undefined;s.quizEndsAt=Date.now()+QUIZ_MS;s.question=publicQuestion(questions[s.questionIndex%questions.length]);for(const p of s.players){p.answered=!p.alive;p.coefficient=p.alive?undefined:0}}
 private coefficientFromDeadline(s:RoomState){if(!s.quizEndsAt)return 0;const n=Math.max(0,Math.ceil((s.quizEndsAt-Date.now())/1000));return n>=7?4:n>=5?3:n>=3?2:n>=1?1:0}
 private applyAction(a:Player,s:RoomState){const action=a.action,c=clampCoefficient(a.coefficient??0);if(!action||c<=0||!a.alive)return `${a.name} 本回合沒有行動。`;const targets=s.players.filter(p=>p.id!==a.id&&p.alive),mul=action==='attack'&&a.jobId==='archer'?1.6:action==='heal'&&a.jobId==='priest'?1.8:action==='finish'&&a.jobId==='assassin'?1.35:1;if(action==='upgrade'){const hp=Math.round((a.jobId==='warrior'?8:4)*c),atk=Math.round((a.jobId==='assassin'?3:1)*c),def=Math.round((a.jobId==='fighter'?3:1)*c);a.maxHp+=hp;a.hp+=hp;a.atk+=atk;a.def+=def;return `${a.name} 升級：HP +${hp}、ATK +${atk}、DEF +${def}`};if(action==='heal'){const amount=Math.round((14+a.atk*.45)*c*mul);if(a.hp>=a.maxHp){const gain=Math.max(1,Math.round(amount*.5));a.maxHp+=gain;a.hp+=gain;return `${a.name} 滿血治療，生命上限 +${gain}`};const before=a.hp;a.hp=Math.min(a.maxHp,a.hp+amount);return `${a.name} 恢復 ${a.hp-before} HP`};if(action==='guard'){a.guard=true;return `${a.name} 進入減傷狀態。`};if(!targets.length)return `${a.name} 找不到攻擊目標。`;if(action==='attack'&&a.jobId==='mage'){let total=0,ko=0;for(const t of targets){const raw=Math.max(1,Math.round(a.atk*c*.45-t.def*.5)),damage=t.guard?Math.max(1,Math.round(raw*.5)):raw;t.guard=false;t.hp=Math.max(0,t.hp-damage);t.alive=t.hp>0;total+=damage;if(!t.alive)ko++}return `${a.name} 施放範圍魔法，攻擊全體 ${targets.length} 人，共造成 ${total} 傷害${ko?`（擊倒 ${ko} 人）`:''}`};const t=[...targets].sort((x,y)=>action==='attack'?y.hp-x.hp:x.hp-y.hp)[0],raw=Math.max(1,Math.round(a.atk*c*(action==='finish'?1.15:1)*mul-t.def)),damage=t.guard?Math.max(1,Math.round(raw*.5)):raw;t.guard=false;t.hp=Math.max(0,t.hp-damage);t.alive=t.hp>0;return `${a.name} ${action==='finish'?'尾刀':'攻擊'} ${t.name}，造成 ${damage} 傷害${t.alive?'':'（擊倒）'}`}
 private resolveRound(s:RoomState){s.battlePhase='resolve';s.actionEndsAt=undefined;s.quizEndsAt=undefined;for(const p of s.players.filter(p=>p.alive))s.log.push(this.applyAction(p,s));s.question=undefined;const living=s.players.filter(p=>p.alive);if(s.round>=10||living.length<=1){s.phase='result';s.log.push('對戰結束！');return}s.round++;s.questionIndex++;this.beginAction(s)}
 private advanceTimeouts(s:RoomState){const now=Date.now();if(s.phase==='jobs'&&s.jobsEndsAt&&now>=s.jobsEndsAt){this.fillRandomJobs(s);this.startBattle(s);return true}if(s.phase!=='battle')return false;if(s.battlePhase==='action'&&s.actionEndsAt&&now>=s.actionEndsAt){for(const p of s.players.filter(p=>p.alive))if(!p.action)p.action='upgrade';this.prepareQuiz(s);s.log.push('動作時間到，未選擇者自動使用升級。');return true}if(s.battlePhase==='quiz'&&s.quizEndsAt&&now>=s.quizEndsAt){for(const p of s.players.filter(p=>p.alive))if(!p.answered){p.answered=true;p.coefficient=0}s.log.push('答題時間到，未作答者本回合無動作。');this.resolveRound(s);return true}return false}
 async fetch(request:Request):Promise<Response>{const url=new URL(request.url),s=await this.getState(url.searchParams.get('roomId')||undefined);if(url.pathname==='/ws'){if(request.headers.get('Upgrade')!=='websocket')return new Response('Expected websocket',{status:426});const playerId=url.searchParams.get('playerId')||'';const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.ctx.acceptWebSocket(server);server.serializeAttachment({playerId});const p=s.players.find(x=>x.id===playerId);if(p){p.lastSeen=Date.now();await this.save(s)}server.send(JSON.stringify({type:'state',state:s}));return new Response(null,{status:101,webSocket:client})}if(url.pathname==='/state'&&request.method==='GET'){const changed=this.pruneStale(s)||this.advanceTimeouts(s);if(changed)await this.save(s);return json(s)}if(url.pathname==='/tick'&&request.method==='POST'){const changed=this.pruneStale(s)||this.advanceTimeouts(s);if(changed)await this.save(s);return json(s)}
 if(url.pathname==='/join'&&request.method==='POST'){const b=await request.json() as {playerId?:string;name?:string},playerId=(b.playerId||crypto.randomUUID()).trim(),name=(b.name||'').trim().slice(0,12);if(!name)return json({error:'Name required'},400);this.pruneStale(s);const existing=s.players.find(p=>p.id===playerId);if(existing){existing.name=name;existing.lastSeen=Date.now();await this.save(s);return json({playerId,state:s})}if(s.phase!=='lobby')return json({error:'Game already started'},409);if(s.players.length>=4)return json({error:'Room full'},409);s.players.push({id:playerId,name,host:s.players.length===0,hp:100,maxHp:100,atk:10,def:5,alive:true,guard:false,lastSeen:Date.now()});await this.save(s);return json({playerId,state:s})}
 if(url.pathname==='/word-pool'&&request.method==='POST'){const b=await request.json() as {playerId?:string;wordPoolSize?:number},p=s.players.find(x=>x.id===b.playerId);if(!p?.host)return json({error:'Host only'},403);if(s.phase!=='lobby')return json({error:'Room not in lobby'},409);const size=Number(b.wordPoolSize) as WordPoolSize;if(!wordPoolSizes.has(size))return json({error:'Invalid word pool'},400);s.wordPoolSize=size;p.lastSeen=Date.now();await this.save(s);return json(s)}
 if(url.pathname==='/begin-jobs'&&request.method==='POST'){const b=await request.json() as {playerId?:string},p=s.players.find(x=>x.id===b.playerId);if(!p?.host)return json({error:'Host only'},403);if(s.phase!=='lobby')return json({error:'Room not in lobby'},409);if(s.players.length<2)return json({error:'Need at least 2 players'},409);for(const x of s.players)x.jobId=undefined;s.phase='jobs';s.jobsEndsAt=Date.now()+JOBS_MS;await this.save(s);return json(s)}
 if(url.pathname==='/choose-job'&&request.method==='POST'){if(this.advanceTimeouts(s)){await this.save(s);return json(s)}const b=await request.json() as {playerId?:string;jobId?:string},p=s.players.find(x=>x.id===b.playerId);if(!p)return json({error:'Player not found'},404);if(s.phase!=='jobs')return json({error:'Not choosing jobs'},409);if(!b.jobId||!jobs.has(b.jobId))return json({error:'Invalid job'},400);if(s.players.some(x=>x.id!==p.id&&x.jobId===b.jobId))return json({error:'Profession already chosen'},409);p.jobId=b.jobId;p.lastSeen=Date.now();if(s.players.every(x=>x.jobId))this.startBattle(s);await this.save(s);return json(s)}
 if(url.pathname==='/start'&&request.method==='POST'){const b=await request.json() as {playerId?:string},p=s.players.find(x=>x.id===b.playerId);if(!p?.host)return json({error:'Host only'},403);if(s.players.length<2)return json({error:'Need at least 2 players'},409);this.fillRandomJobs(s);this.startBattle(s);await this.save(s);return json(s)}
 if(url.pathname==='/action'&&request.method==='POST'){if(this.advanceTimeouts(s)){await this.save(s);return json(s)}if(s.phase!=='battle'||s.battlePhase!=='action')return json({error:'Not accepting actions'},409);const b=await request.json() as {playerId?:string;action?:ActionName},p=s.players.find(x=>x.id===b.playerId);if(!p?.alive)return json({error:'Player not available'},404);if(!b.action||!actions.has(b.action))return json({error:'Invalid action'},400);p.lastSeen=Date.now();p.action=b.action;if(s.players.filter(x=>x.alive).every(x=>x.action))this.prepareQuiz(s);await this.save(s);return json(s)}
 if(url.pathname==='/answer'&&request.method==='POST'){if(this.advanceTimeouts(s)){await this.save(s);return json(s)}if(s.phase!=='battle'||s.battlePhase!=='quiz')return json({error:'Not accepting answers'},409);const b=await request.json() as {playerId?:string;choice?:string},p=s.players.find(x=>x.id===b.playerId);if(!p?.alive)return json({error:'Player not available'},404);if(p.answered)return json({error:'Already answered'},409);p.lastSeen=Date.now();const q=questions[s.questionIndex%questions.length];p.answered=true;p.coefficient=b.choice===q.answer?this.coefficientFromDeadline(s):0;if(s.players.filter(x=>x.alive).every(x=>x.answered))this.resolveRound(s);await this.save(s);return json(s)}
 if(url.pathname==='/leave'&&request.method==='POST'){const b=await request.json() as {playerId?:string};s.players=s.players.filter(x=>x.id!==b.playerId);this.normalizeAfterLeave(s);await this.save(s);return json(s)}
 if(url.pathname==='/reset'&&request.method==='POST'){const b=await request.json() as {playerId?:string},p=s.players.find(x=>x.id===b.playerId);if(!p?.host)return json({error:'Host only'},403);for(const x of s.players){x.jobId=undefined;x.hp=100;x.maxHp=100;x.atk=10;x.def=5;x.alive=true;x.guard=false;x.action=undefined;x.answered=false;x.coefficient=undefined;x.lastSeen=Date.now()}s.phase='jobs';s.jobsEndsAt=Date.now()+JOBS_MS;s.round=0;s.question=undefined;s.log=[];s.actionEndsAt=undefined;s.quizEndsAt=undefined;await this.save(s);return json(s)}return json({error:'Not found'},404)}
 async alarm(){const s=await this.getState();const changed=this.pruneStale(s)||this.advanceTimeouts(s);if(changed||s.players.length)await this.save(s)}
 async webSocketMessage(ws:WebSocket,message:string|ArrayBuffer){if(typeof message==='string'&&message==='ping'){const a=ws.deserializeAttachment() as {playerId?:string}|null,s=await this.getState();const p=s.players.find(x=>x.id===a?.playerId);if(p){p.lastSeen=Date.now();await this.save(s)}ws.send('pong')}}
 async webSocketClose(ws:WebSocket){const a=ws.deserializeAttachment() as {playerId?:string}|null;if(!a?.playerId)return;const s=await this.getState();if(s.players.some(p=>p.id===a.playerId)){s.players=s.players.filter(p=>p.id!==a.playerId);this.normalizeAfterLeave(s);await this.save(s)}}
 async webSocketError(ws:WebSocket){await this.webSocketClose(ws)}
}
