import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { connectRoom, hasMultiplayerApi, multiplayerApi, type RemoteAction, type RemoteRoomState, type RoundLimit, type WordPoolSize } from './lib/multiplayer'
import './job-images.css'
import './home-fixes.css'
import './battle-layout.css'
import './battle-refinements.css'

type Page='home'|'rooms'|'lobby'|'jobs'|'battle'|'result'
type Job={id:string;name:string;feature:string;badge:string}
type EffectKind='hit'|'heal'|'ko'|'buff'
type RemotePlayer=RemoteRoomState['players'][number]
const rooms=[{id:'sword',name:'聖劍試煉場',subtitle:'勇者們以榮耀決勝'},{id:'shadow',name:'影刃競技廳',subtitle:'速度與判斷的對決'},{id:'bow',name:'蒼弓決鬥域',subtitle:'遠距決勝的戰場'},{id:'oracle',name:'神諭聖堂',subtitle:'智慧與意志的終局'}]
const jobs:Job[]=[{id:'assassin',name:'刺客',feature:'尾刀與升級攻擊特化',badge:'ATK'},{id:'warrior',name:'戰士',feature:'減傷與升級生命特化',badge:'HP'},{id:'fighter',name:'武道家',feature:'減傷與升級防禦特化',badge:'DEF'},{id:'archer',name:'弓箭手',feature:'攻擊與升級攻擊特化',badge:'DMG'},{id:'priest',name:'牧師',feature:'治療與升級防禦特化',badge:'HEAL'},{id:'mage',name:'法師',feature:'範圍攻擊與升級攻擊特化',badge:'AOE'}]
const actions:{id:RemoteAction;name:string;icon:string;desc:string}[]=[{id:'upgrade',name:'升級',icon:'✦',desc:'增加生命、攻擊、防禦'},{id:'attack',name:'攻擊',icon:'⚔',desc:'攻擊生命最多的玩家'},{id:'heal',name:'治療',icon:'✚',desc:'恢復生命並獲得護盾'},{id:'finish',name:'尾刀',icon:'➶',desc:'攻擊生命最少的玩家'},{id:'guard',name:'減傷',icon:'◆',desc:'降低傷害並永久提升防禦'},{id:'ultimate',name:'絕招',icon:'★',desc:'每場可成功施放兩次'}]
const ultimateNames:Record<string,string>={assassin:'影殺・終結',warrior:'不屈戰魂',archer:'穿雲狙擊',fighter:'金剛不壞',priest:'神聖奇蹟',mage:'末日魔法'}
const wordPoolOptions:WordPoolSize[]=[300,1200,5000]
const roundLimitOptions:RoundLimit[]=[10,20,30]
const fallbackQuestion={id:0,word:'brave',choices:['安靜的','勇敢的','飢餓的']}
const jobName=(id?:string)=>jobs.find(j=>j.id===id)?.name??'尚未選擇'
const jobImage=(id?:string)=>id?`/images/jobs/${id==='mage'?'Mage':id}.png`:''
const jobHeadImage=(id?:string)=>id?`/images/jobs/${id==='mage'?'Magehead':`${id}head`}.png`:''
const roomImage=(id?:string)=>id==='sword'?'/images/rooms/Holy%20Sword.png':id==='shadow'?'/images/rooms/Shadow%20Blade.png':id==='bow'?'/images/rooms/Azure%20Bow.png':id==='oracle'?'/images/rooms/Oracle.png':''
const phasePage=(s:RemoteRoomState):Page=>s.phase==='battle'?'battle':s.phase==='result'?'result':s.phase==='jobs'?'jobs':'lobby'
const actionMeta=(id?:RemoteAction)=>actions.find(a=>a.id===id)
const actionName=(id?:RemoteAction,jobId?:string)=>id==='ultimate'?(ultimateNames[jobId??'']??'絕招'):(actionMeta(id)?.name??'無效')
const signed=(value:number)=>`${value>0?'+':''}${value}`
const effectText=(p?:RemotePlayer)=>[p?.guard?`減傷(${Math.max(1,p.guardCharges??1)})`:'',(p?.shield??0)>0?`護盾 ${p?.shield}`:''].filter(Boolean).join(' ')
const roundLabel=(round:number)=>['','第一回','第二回','第三回','第四回','第五回','第六回','第七回','第八回','第九回','第十回'][round]??`第${round}回`
const createDemoState=(name:string,roomId:string):RemoteRoomState=>({roomId,phase:'lobby',battlePhase:'action',round:0,maxRounds:10,questionIndex:0,wordPoolSize:300,players:[{id:'demo-me',name,host:true,hp:100,maxHp:100,atk:10,def:5,alive:true,guard:false,shield:0,ultimateUsed:false,ultimateUses:0,actionsTaken:0,questionsSeen:0,correctAnswers:0,damageDone:0,healingDone:0},{id:'demo-bot',name:'字典',host:false,jobId:'warrior',hp:100,maxHp:100,atk:10,def:5,alive:true,guard:false,shield:0,ultimateUsed:false,ultimateUses:0,actionsTaken:0,questionsSeen:0,correctAnswers:0,damageDone:0,healingDone:0}],log:[]})

export default function App(){
 const online=hasMultiplayerApi();const[page,setPage]=useState<Page>('home');const[name,setName]=useState(()=>localStorage.getItem('hero-player-name')??'');const[roomId,setRoomId]=useState('');const[playerId,setPlayerId]=useState('');const[roomState,setRoomState]=useState<RemoteRoomState|null>(null);const[jobId,setJobId]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[connected,setConnected]=useState(true);const[roomCounts,setRoomCounts]=useState<Record<string,number>>({});const[clock,setClock]=useState(Date.now());const[effects,setEffects]=useState<Record<string,EffectKind>>({});const[selectedChoice,setSelectedChoice]=useState('');const[wrongFeedback,setWrongFeedback]=useState<{question:typeof fallbackQuestion;correctAnswer:string}|null>(null);const tickRef=useRef('');const spokenQuestionRef=useRef('');const previousStatsRef=useRef<Record<string,{hp:number;maxHp:number;atk:number;def:number;alive:boolean}>>({});const feedbackLockRef=useRef(false);const pendingRoomStateRef=useRef<RemoteRoomState|null>(null)
 const selectedRoom=useMemo(()=>rooms.find(r=>r.id===roomId),[roomId]);const me=roomState?.players.find(p=>p.id===playerId);const liveQuestion=roomState?.questions?.[Math.min(2,me?.quizIndex??0)]??roomState?.question??fallbackQuestion;const question=wrongFeedback?.question??liveQuestion;const sortedResults=[...(roomState?.players??[])].sort((a,b)=>b.hp-a.hp||b.maxHp-a.maxHp||b.atk-a.atk||b.def-a.def);const deadline=roomState?.battlePhase==='quiz'?(me?.quizQuestionStartedAt?me.quizQuestionStartedAt+5000:roomState.quizEndsAt):roomState?.battlePhase==='resolve'?roomState.resolveEndsAt:roomState?.actionEndsAt;const remainingSeconds=deadline?Math.max(0,Math.ceil((deadline-clock)/1000)):roomState?.battlePhase==='quiz'?5:roomState?.battlePhase==='action'?5:0;const latestLog=roomState?.log.at(-1)??''
 useEffect(()=>{localStorage.removeItem('hero-room-id');localStorage.removeItem('hero-player-id');setPlayerId('');const hash=new URLSearchParams(window.location.hash.replace(/^#/,''));const lineName=hash.get('line_login'),lineError=hash.get('line_error');if(lineName){const n=lineName.trim().slice(0,12);if(n){localStorage.setItem('hero-player-name',n);setName(n);setError('');setPage('rooms')}}else if(lineError)setError('LINE 登入失敗，請再試一次');if(lineName||lineError)window.history.replaceState(null,'',window.location.pathname+window.location.search)},[])
 useEffect(()=>{if(!online||!roomId||!playerId)return;return connectRoom(roomId,next=>{if(feedbackLockRef.current){pendingRoomStateRef.current=next;return}setRoomState(next)},setConnected)},[online,roomId,playerId])
 useEffect(()=>{if(roomState)setPage(phasePage(roomState))},[roomState?.phase])
 useEffect(()=>{if(!online||page!=='battle'||!roomId)return;let cancelled=false;const sync=async()=>{try{const next=await multiplayerApi.state(roomId);if(cancelled)return;if(feedbackLockRef.current){pendingRoomStateRef.current=next;return}setRoomState(next);if(next.phase==='result')setPage('result')}catch{}};const t=window.setInterval(()=>void sync(),1000);return()=>{cancelled=true;window.clearInterval(t)}},[online,page,roomId])
 useEffect(()=>{if(!online||page!=='rooms')return;let cancelled=false;const load=async()=>{const entries=await Promise.all(rooms.map(async r=>{try{return[r.id,(await multiplayerApi.state(r.id)).players.length]as const}catch{return[r.id,0]as const}}));if(!cancelled)setRoomCounts(Object.fromEntries(entries))};void load();const t=window.setInterval(()=>void load(),3000);return()=>{cancelled=true;window.clearInterval(t)}},[online,page])
 useEffect(()=>{if(page!=='battle'&&page!=='jobs')return;const t=window.setInterval(()=>setClock(Date.now()),120);return()=>window.clearInterval(t)},[page])
 useEffect(()=>{if(!online||page!=='battle'||!roomState||!deadline||remainingSeconds>0)return;const key=`${roomState.round}-${roomState.battlePhase}-${deadline}`;if(tickRef.current===key)return;tickRef.current=key;void multiplayerApi.tick(roomId).then(next=>{if(feedbackLockRef.current){pendingRoomStateRef.current=next;return}setRoomState(next);if(next.phase==='result')setPage('result')}).catch(()=>undefined)},[online,page,roomState?.round,roomState?.battlePhase,deadline,remainingSeconds,roomId])
 useEffect(()=>{if(page!=='battle'||roomState?.battlePhase!=='quiz'||!question?.id||!me?.alive||me?.answered)return;const key=`${roomState.round}:${question.id}`;if(spokenQuestionRef.current===key)return;spokenQuestionRef.current=key;const t=window.setTimeout(()=>{if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(question.word);u.lang='en-US';u.rate=.82;window.speechSynthesis.speak(u)},120);return()=>window.clearTimeout(t)},[page,roomState?.round,roomState?.battlePhase,question.id,me?.alive,me?.answered])
 useEffect(()=>setSelectedChoice(''),[question.id,roomState?.round])
 useEffect(()=>{if(!roomState)return;const prev=previousStatsRef.current,next:Record<string,{hp:number;maxHp:number;atk:number;def:number;alive:boolean}>={},changed:Record<string,EffectKind>={};for(const p of roomState.players){const old=prev[p.id];if(old){if(old.alive&&!p.alive)changed[p.id]='ko';else if(p.hp<old.hp)changed[p.id]='hit';else if(p.hp>old.hp)changed[p.id]='heal';else if(p.maxHp>old.maxHp||p.atk>old.atk||p.def>old.def)changed[p.id]='buff'}next[p.id]={hp:p.hp,maxHp:p.maxHp,atk:p.atk,def:p.def,alive:p.alive}}previousStatsRef.current=next;if(Object.keys(changed).length){setEffects(changed);const t=window.setTimeout(()=>setEffects({}),850);return()=>window.clearTimeout(t)}},[roomState?.players.map(p=>`${p.id}:${p.hp}:${p.maxHp}:${p.atk}:${p.def}:${p.alive}`).join('|')])
 const run=async(task:()=>Promise<void>)=>{setBusy(true);setError('');try{await task()}catch(e){setError(e instanceof Error?e.message:'連線發生錯誤')}finally{setBusy(false)}}
 const syncBattleSilently=async()=>{if(!online||!roomId)return;try{const next=await multiplayerApi.state(roomId);if(feedbackLockRef.current){pendingRoomStateRef.current=next;return}setRoomState(next);setPage(phasePage(next));setError('')}catch{}}
 const isPhaseTransitionError=(message:string)=>/not accepting (actions|answers)/i.test(message)
 const enterGame=()=>{const n=name.trim();if(!n)return;localStorage.setItem('hero-player-name',n);setName(n);setPage('rooms')}
 const enterRoom=async(nextRoomId=roomId)=>{if(!nextRoomId||busy)return;setRoomId(nextRoomId);if(!online){const demo=createDemoState(name,nextRoomId);setPlayerId('demo-me');setRoomState(demo);setPage('lobby');return}await run(async()=>{const joined=await multiplayerApi.join(nextRoomId,name);setPlayerId(joined.playerId);setRoomState(joined.state);setPage(phasePage(joined.state));localStorage.setItem('hero-player-id',joined.playerId);localStorage.setItem('hero-room-id',nextRoomId)})}
 const selectWordPool=async(size:WordPoolSize)=>{if(!roomState||!me?.host||busy)return;if(!online){setRoomState({...roomState,wordPoolSize:size});return}await run(async()=>setRoomState(await multiplayerApi.setWordPool(roomId,playerId,size)))}
 const selectRoundLimit=async(limit:RoundLimit)=>{if(!roomState||!me?.host||busy)return;if(!online){setRoomState({...roomState,maxRounds:limit});return}await run(async()=>setRoomState(await multiplayerApi.setRoundLimit(roomId,playerId,limit)))}
 const beginJobs=async()=>{if(!roomState)return;if(!online){setRoomState({...roomState,phase:'jobs',jobsEndsAt:Date.now()+30000});setPage('jobs');return}await run(async()=>setRoomState(await multiplayerApi.beginJobs(roomId,playerId)))}
 const chooseJob=async(nextJobId:string)=>{if(!roomState)return;const taken=roomState.players.some(p=>p.id!==playerId&&p.jobId===nextJobId);if(taken)return;setJobId(nextJobId);if(!online){const nextState={...roomState,phase:'battle'as const,battlePhase:'action'as const,round:1,actionEndsAt:Date.now()+5000,players:roomState.players.map(p=>p.id===playerId?{...p,jobId:nextJobId,ultimateUsed:false,ultimateUses:0,actionsTaken:0,shield:0}:p),log:['本機示範模式']};setRoomState(nextState);setPage('battle');return}await run(async()=>setRoomState(await multiplayerApi.chooseJob(roomId,playerId,nextJobId)))}
 const submitAction=async(action:RemoteAction)=>{if(!roomState||me?.action||(action==='ultimate'&&(me?.ultimateUses??0)>=2))return;if(!online){setRoomState({...roomState,players:roomState.players.map(p=>p.id===playerId?{...p,action}:p)});return}setError('');try{setRoomState(await multiplayerApi.action(roomId,playerId,action))}catch(e){const message=e instanceof Error?e.message:'動作送出失敗';if(isPhaseTransitionError(message)){await syncBattleSilently();return}setError(message)}}
 const submitAnswer=async(choice:string)=>{if(!roomState||me?.answered||wrongFeedback)return;const answeredQuestion=question;setSelectedChoice(choice);if(!online){setRoomState({...roomState,players:roomState.players.map(p=>p.id===playerId?{...p,answered:true,answerCorrect:choice==='勇敢的',coefficient:choice==='勇敢的'?1:0,answeredAt:Date.now()}:p)});return}setError('');try{const next=await multiplayerApi.answer(roomId,playerId,choice,0),feedback=next.answerFeedback;if(feedback&&!feedback.correct){try{const audio=new Audio('/music/wrong.mp3');audio.volume=.95;void audio.play().catch(()=>undefined)}catch{}feedbackLockRef.current=true;pendingRoomStateRef.current=next;setWrongFeedback({question:answeredQuestion,correctAnswer:feedback.correctAnswer});window.setTimeout(()=>{setWrongFeedback(null);setSelectedChoice('');feedbackLockRef.current=false;const pending=pendingRoomStateRef.current;pendingRoomStateRef.current=null;if(pending){setRoomState(pending);setPage(phasePage(pending));setError('')}else void syncBattleSilently()},1000);return}setWrongFeedback(null);setSelectedChoice('');setRoomState(next)}catch(e){feedbackLockRef.current=false;pendingRoomStateRef.current=null;const message=e instanceof Error?e.message:'答案送出失敗';if(isPhaseTransitionError(message)){await syncBattleSilently();return}setError(message)}}
 const leaveRoom=async()=>{feedbackLockRef.current=false;pendingRoomStateRef.current=null;if(online&&roomId&&playerId){try{await multiplayerApi.leave(roomId,playerId)}catch{}}localStorage.removeItem('hero-room-id');localStorage.removeItem('hero-player-id');setRoomState(null);setRoomId('');setPlayerId('');setJobId('');setPage('rooms')}
 if(page==='rooms')return <main className="page-shell rooms-page"><section className="page-card rooms-card"><button className="back-button" onClick={()=>setPage('home')} type="button">← 返回</button><div className="room-grid">{rooms.map(r=><button key={r.id} className="room-card" onClick={()=>void enterRoom(r.id)} type="button" disabled={busy||(online&&(roomCounts[r.id]??0)>=5)} aria-label={r.name}/>)}</div><ErrorBox text={error}/></section></main>
 if(page==='lobby'){const players=roomState?.players??[];return <main className="page-shell lobby-page"><section className="page-card lobby-card"><button className="back-button" onClick={()=>void leaveRoom()} type="button">← 返回</button><img className="lobby-room-image" src={roomImage(roomId)} alt={selectedRoom?.name??'房間'}/>{me?.host&&<><div className="word-pool-selector" role="group" aria-label="單字題庫數量">{wordPoolOptions.map(size=><button key={size} className={`word-pool-button ${roomState?.wordPoolSize===size?'selected':''}`} type="button" disabled={busy} onClick={()=>void selectWordPool(size)}>{size}</button>)}</div><div className="word-pool-selector round-limit-selector" role="group" aria-label="遊戲回合數">{roundLimitOptions.map(limit=><button key={limit} className={`word-pool-button ${roomState?.maxRounds===limit?'selected':''}`} type="button" disabled={busy} onClick={()=>void selectRoundLimit(limit)}>{limit}回</button>)}</div></>}<div className="player-list lobby-player-list">{players.map(p=><PlayerRow key={p.id} player={p} label={p.host?'房主':undefined} textOnly/>)}{Array.from({length:Math.max(0,5-players.length)}).map((_,i)=><PlayerRow key={i} name="等待玩家加入…" muted textOnly/>)}</div><ErrorBox text={error}/>{me?.host&&<button className="primary-button lobby-start-button" disabled={busy} onClick={()=>void beginJobs()} type="button">開戰</button>}</section></main>}
 if(page==='jobs'){const taken=new Set((roomState?.players??[]).filter(p=>p.id!==playerId&&p.jobId).map(p=>p.jobId));return <main className="page-shell jobs-page"><section className="page-card jobs-card"><button className="back-button" onClick={()=>void leaveRoom()} type="button">← 返回</button><div className="job-grid">{jobs.map(j=>{const isTaken=taken.has(j.id),selected=(me?.jobId??jobId)===j.id;return <button key={j.id} className={`job-card job-art-card ${selected?'selected':''} ${isTaken?'taken':''}`} onClick={()=>void chooseJob(j.id)} type="button" disabled={busy||isTaken||Boolean(me?.jobId)} aria-label={j.name}><img className="job-full-art" src={jobImage(j.id)} alt={j.name}/></button>})}</div><ErrorBox text={error}/></section></main>}
 if(page==='battle'&&roomState){const myEffect=me?effects[me.id]:undefined;const resolving=roomState.battlePhase==='resolve';return <main className="battle-shell"><section className={`status-card self-card character-status-card ${myEffect?`fx-${myEffect}`:''}`}><CharacterHead player={me} size="large"/><PlayerStatus player={me} fallbackName={name}/></section><section className="enemy-strip">{roomState.players.filter(p=>p.id!==playerId).map(p=><PlayerBattle key={p.id} player={p} effect={effects[p.id]}/>)}</section><div className="battle-meta-row"><span className="battle-round">{roundLabel(roomState.round)}</span><span className={`battle-meta-timer ${remainingSeconds<=2?'danger':''}`}>{!resolving?remainingSeconds:''}</span><span className="battle-meta-space" aria-hidden="true"/></div><section className={`battle-panel ${resolving?'resolve-panel':''}`}><div className="battle-heading"><div><h1>{roomState.battlePhase==='quiz'?'英文挑戰':resolving?'戰鬥結果':'選擇動作'}</h1></div></div>{roomState.battlePhase==='action'&&me?.alive&&<div className="action-grid">{actions.map(a=>{const ultimate=a.id==='ultimate',uses=me.ultimateUses??0,spent=uses>=2,disabled=Boolean(me.action)||(ultimate&&spent);return <button key={a.id} className={`action-card ${ultimate?'ultimate-action':''} ${me.action===a.id?'selected':''} ${ultimate&&spent?'spent':''}`} disabled={disabled} onClick={()=>void submitAction(a.id)} type="button"><span className="action-icon">{a.icon}</span><strong>{ultimate?(ultimateNames[me.jobId??'']??'絕招'):a.name}</strong><small>{ultimate?(spent?'本場 2 次已使用':`本場已使用 ${uses}/2 次`):a.desc}</small></button>})}</div>}{roomState.battlePhase==='quiz'&&me?.alive&&<div className={`quiz-card ${me?.answered?'quiz-complete':''}`}><div className="word-line"><strong className="word">{question.word}</strong></div><div className="answer-grid">{question.choices.map((c,i)=><button key={c} className={`answer-choice answer-choice-${i+1} ${selectedChoice===c?'chosen':''} ${wrongFeedback?.correctAnswer===c?'correct-answer':''} ${(wrongFeedback&&wrongFeedback.correctAnswer!==c)||(selectedChoice&&selectedChoice!==c)?'dimmed':''}`} type="button" disabled={Boolean(me.answered)||Boolean(wrongFeedback)||remainingSeconds<=0} onClick={()=>void submitAnswer(c)}>{c}</button>)}</div></div>}{resolving&&<BattleResultCapsule state={roomState}/>} {!me?.alive&&!resolving&&<div className="notice-box">你已被擊倒，可以觀看剩餘玩家完成對戰。</div>}{!resolving&&latestLog&&<div className={`action-banner ${latestLog.includes('擊倒')?'ko-banner':''}`}>{latestLog}</div>}<ErrorBox text={error}/>{!resolving&&roomState.log.length>1&&<div className="battle-log">{roomState.log.slice(-5).reverse().map((line,i)=><p key={`${line}-${i}`}>{line}</p>)}</div>}</section></main>}
 if(page==='result')return <Screen title="對戰結果" subtitle="排行榜依剩餘生命值決定" onBack={()=>void leaveRoom()}><div className="ranking-list result-ranking-list">{sortedResults.map((p,i)=><ResultPlayerCard key={p.id} player={p} rank={i+1}/>)}</div>{me?.host&&online?<button className="primary-button result-replay-button" type="button" onClick={()=>void run(async()=>setRoomState(await multiplayerApi.reset(roomId,playerId)))}>再戰一場</button>:<button className="primary-button result-replay-button" type="button" onClick={()=>void leaveRoom()}>返回房間選擇</button>}</Screen>
 return <main className="app-shell"><section className="hero-card"><p className="eyebrow">ENGLISH WORD BATTLE</p><h1>勇者</h1><p className="subtitle">1～5 人英文單字對戰遊戲</p><div className="login-panel"><label className="field-label" htmlFor="player-name">勇者名稱</label><input id="player-name" className="name-input" type="text" maxLength={12} placeholder="輸入你的名字" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&enterGame()}/><div className="divider"><span>或</span></div><a className="line-button" href="/auth/line" aria-label="使用 LINE 登入"><img src="/images/home/line.png" alt="LINE" /></a></div><button className="primary-button" type="button" disabled={!name.trim()} onClick={enterGame} aria-label="開始冒險，選擇房間">開始冒險</button><p className="hint">{online?'Cloudflare 即時多人模式已啟用。':'本機示範模式'}</p></section></main>
}

function BattleResultCapsule({state}:{state:RemoteRoomState}){const result=state.currentResult;if(!result)return <div className="result-capsule waiting"><strong>準備結算…</strong></div>;const actor=state.players.find(p=>p.id===result.playerId);const meta=actionMeta(result.action);const step=(state.resolveIndex??0)+1,total=state.resolveQueue?.length??0;return <div key={result.id} className={`result-capsule result-${result.action??'none'} ${result.correct?'correct':'wrong'} ${result.critical?'critical':''} ${result.ultimate?'ultimate-result':''}`}>{result.critical&&<div className="critical-burst">爆擊！</div>}{result.ultimate&&<div className="ultimate-burst">絕招</div>}<div className="result-capsule-top"><CharacterHead player={actor} size="large"/><div className="result-actor-copy"><span className="mini-label">ACTION {step} / {total}</span><strong>{result.playerName}</strong><small>{jobName(actor?.jobId)}</small></div><div className="result-action-mark"><span>{meta?.icon??'×'}</span><b>{actionName(result.action,actor?.jobId)}</b><em>×{result.coefficient}{result.critical?' ×1.5':''}</em></div></div><p className="result-main-text">{result.text}</p><div className="result-change-list">{result.changes.length?result.changes.map(change=>{const lifeChange=change.hp??change.maxHp;return <div key={`${result.id}-${change.playerId}`} className={`result-change-chip ${change.ko?'ko':''}`}><strong>{change.name}</strong>{lifeChange!==undefined&&<span className="change-stat change-hp">{signed(lifeChange)}</span>}{change.atk!==undefined&&<span className="change-stat change-atk">{signed(change.atk)}</span>}{change.def!==undefined&&<span className="change-stat change-def">{signed(change.def)}</span>}{change.shield!==undefined&&<span className="change-status">護盾 {signed(change.shield)}</span>}{change.guard&&<span className="change-status">{change.guard==='on'?'獲得減傷效果':'減傷效果結束'}</span>}{change.ko&&<span className="change-status ko-text">擊倒</span>}</div>}):<div className="result-no-change">失敗、無法行動</div>}</div></div>}
function Screen({title,subtitle,onBack,children}:{title:string;subtitle:string;onBack:()=>void;children:ReactNode}){return <main className="page-shell result-page"><section className="page-card final-ranking-card"><button className="back-button" onClick={onBack} type="button">← 返回</button><div className="result-content"><p className="eyebrow">HERO WORD BATTLE</p><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p>{children}</div></section></main>}
function CharacterHead({player,size='small'}:{player?:RemotePlayer;size?:'small'|'large'}){if(!player?.jobId)return <span className={`character-head-placeholder ${size}`}/>;return <img className={`character-head ${size}`} src={jobHeadImage(player.jobId)} alt={jobName(player.jobId)}/>}
function PlayerRow({player,name,label,muted=false,textOnly=false}:{player?:RemotePlayer;name?:string;label?:string;muted?:boolean;textOnly?:boolean}){return <div className={`player-row ${textOnly?'':'player-row-with-head'} ${muted?'muted':''}`}>{!textOnly&&(player?<CharacterHead player={player}/>:<span className="player-dot"/>)}<strong>{player?.name??name}</strong>{label&&<em>{label}</em>}</div>}
function StatDisplay({kind,value}:{kind:'life'|'atk'|'def';value:string|number}){const src=kind==='life'?'/images/actions/life.png':kind==='atk'?'/images/actions/ATK.png':'/images/actions/DEF.png';const alt=kind==='life'?'生命':kind==='atk'?'攻擊':'防禦';return <span className={`player-stat player-stat-${kind}`}><img src={src} alt={alt}/><b>{value}</b></span>}
function PlayerStatus({player,fallbackName}:{player?:RemotePlayer;fallbackName?:string}){return <div className="player-status-grid"><div className="player-status-top"><strong className="player-status-name">{player?.name??fallbackName??''}</strong><StatDisplay kind="atk" value={player?.atk??10}/><StatDisplay kind="def" value={player?.def??5}/></div><div className="player-status-bottom"><span className="player-job-name">{jobName(player?.jobId)}</span><StatDisplay kind="life" value={`${player?.hp??0}/${player?.maxHp??100}`}/><span className="player-effect-status">{effectText(player)}</span></div></div>}
function PlayerBattle({player,effect}:{player:RemotePlayer;effect?:EffectKind}){return <div className={`enemy-card enemy-card-with-head ${!player.alive?'muted':''} ${effect?`fx-${effect}`:''}`}><CharacterHead player={player}/><PlayerStatus player={player}/></div>}
function ResultPlayerCard({player,rank}:{player:RemotePlayer;rank:number}){const seen=player.questionsSeen??0,correct=player.correctAnswers??0,accuracy=seen?Math.round(correct/seen*100):0;return <div className={`result-player-card ${rank===1?'champion':''}`}><div className="result-rank-badge">{rank===1?'🏆':rank}</div><CharacterHead player={player} size="large"/><PlayerStatus player={player}/><div className="result-performance"><span>答對率 <b>{accuracy}%</b></span><span>輸出傷害 <b>{player.damageDone??0}</b></span><span>治療量 <b>{player.healingDone??0}</b></span></div></div>}
function ErrorBox({text}:{text:string}){return text?<div className="notice-box">⚠️ {text}</div>:null}
